// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr42ddq4qFeFpklMTHoL-YZGKF1w0-WXI',
    appId: '1:210024593514:web:91fd5d4eb4d556ccb2b213',
    messagingSenderId: '210024593514',
    projectId: 'aarthik-udaan-clean',
    authDomain: 'aarthik-udaan-clean.firebaseapp.com',
    storageBucket: 'aarthik-udaan-clean.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmeYAOtNX6Lws04_WA99HMK9Vg0pCNij0',
    appId: '1:210024593514:android:51eb5384e8af7ffbb2b213',
    messagingSenderId: '210024593514',
    projectId: 'aarthik-udaan-clean',
    storageBucket: 'aarthik-udaan-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmcgRjoBj0xh_WsCTlhvKoF6rXZV7n1HY',
    appId: '1:210024593514:ios:f0d62b4bdee403f2b2b213',
    messagingSenderId: '210024593514',
    projectId: 'aarthik-udaan-clean',
    storageBucket: 'aarthik-udaan-clean.firebasestorage.app',
    iosBundleId: 'com.example.iserveu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr42ddq4qFeFpklMTHoL-YZGKF1w0-WXI',
    appId: '1:210024593514:web:303bcf0f308ce9b7b2b213',
    messagingSenderId: '210024593514',
    projectId: 'aarthik-udaan-clean',
    authDomain: 'aarthik-udaan-clean.firebaseapp.com',
    storageBucket: 'aarthik-udaan-clean.firebasestorage.app',
  );

}